# Generated by Django 6.0.2 on 2026-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
    ]
