# Generated by Django 6.0.2 on 2026-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_student_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("stock", models.PositiveIntegerField()),
            ],
        ),
    ]
