# Generated by Django 6.0.2 on 2026-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("ELEC", "Electronics"),
                            ("CIVIL", "Civil Engineering"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
